### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Royalgamer06** [ArneVogel/concat#11]
Somehow (I think recent) twitch videos don't download:
```

>concat_win.exe -vod 180380104
Contacting Twitch Server
Selected quality: chunked
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x797f40, 0xc082002050)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3f4
main.downloadPartVOD(0xc082002250, 0x9, 0x80b278, 0x1, 0x80dd48, 0x4, 0x80d5d0, 0x7)
        /home/arne/Dokumente/go/src/github.com/arnevogel/concat/main.go:355 +0x2816
main.main()
        /home/arne/Dokumente/go/src/github.com/arnevogel/concat/main.go:494 +0x499

>concat_win.exe -vod 179341125
Contacting Twitch Server
Selected quality: chunked
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x797f40, 0xc082002050)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3f4
main.downloadPartVOD(0xc082002250, 0x9, 0x80b278, 0x1, 0x80dd48, 0x4, 0x80d5d0, 0x7)
        /home/arne/Dokumente/go/src/github.com/arnevogel/concat/main.go:355 +0x2816
main.main()
        /home/arne/Dokumente/go/src/github.com/arnevogel/concat/main.go:494 +0x499
```

**Comment by Minkafighter** [comment]
can confirm, same error happens to me too

**Comment by Royalgamer06** [comment]
Shame, because I was about to make a nodejs library from it.

**Comment by ArneVogel** [comment]
Thanks for reporting this. New release with the bugfix: https://github.com/ArneVogel/concat/releases

This was caused by twitch changing the name scheme for their edgecast urls. I tested the fix with the vod you had your problem with and it works now.
